import { Component } from '@angular/core';
import { AutoHeightDirective } from './auto-height.directive';

@Component({
  standalone: true,
  selector: 'app-auto-height-demo',
  templateUrl: './auto-height.component.html',
  styleUrls: ['./auto-height.component.scss'],
  imports: [AutoHeightDirective],
})
export class AutoHeightDemoComponent {
  public paragraph1 = `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).`;

  public paragraph2 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris fermentum euismod enim, vel rutrum arcu. Pellentesque cursus nec sem dictum tincidunt. In hac habitasse platea dictumst. Nunc cursus quam quis blandit posuere. Sed feugiat ligula magna, quis imperdiet tortor imperdiet eleifend. In auctor fringilla dolor, ut maximus massa viverra sit amet. Fusce eget tempor tellus, quis congue leo. Phasellus sed nulla dictum, hendrerit velit eu, mattis eros.
      Quisque arcu arcu, elementum ut nisl vel, sagittis tincidunt tellus. Suspendisse mi mauris, euismod nec tortor iaculis, pellentesque varius felis. Vestibulum pulvinar eros diam. Sed sed porttitor sapien. Aliquam erat volutpat. Mauris interdum laoreet ligula, non lobortis libero convallis ornare. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In nec odio elit. Quisque ut erat velit. Integer ac commodo sapien, eu ullamcorper est.
      In non efficitur nisi, ut eleifend sapien. Etiam mi magna, laoreet a rutrum a, dignissim sit amet arcu. Phasellus ex mauris, feugiat vitae odio dictum, condimentum viverra leo. Pellentesque mattis tempor enim eu convallis. In imperdiet pellentesque risus, iaculis aliquet purus dapibus quis. Quisque a pellentesque nisl. Cras eu neque dictum, eleifend nulla in, fringilla mauris.
      Cras tellus libero, finibus vel mi at, mollis lacinia augue. Pellentesque et lacus massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum vulputate eu dui sed condimentum. Nullam quis est urna. Integer scelerisque elit eget semper molestie. Curabitur bibendum accumsan sodales. Donec non pellentesque purus. Ut sagittis feugiat quam sed maximus. In mattis nunc sapien, vitae bibendum ligula iaculis accumsan. Praesent condimentum sit amet urna non fringilla. Vestibulum ultrices augue in diam vestibulum, non fermentum nibh pretium. Sed bibendum efficitur eros ac laoreet. Aliquam ac leo vel libero ornare iaculis in eget orci. Vivamus sed tellus erat. Donec sed gravida ligula, quis ultrices lectus
      Nulla facilisi. Ut luctus eu ipsum non facilisis. Donec eleifend consectetur purus. Donec lacinia purus a ex lacinia feugiat. Donec in gravida augue. Maecenas lacinia quam a neque tempor tempor. Quisque ac dapibus urna, quis varius magna. Morbi vitae lectus massa. Proin faucibus, nulla vitae aliquam mollis, ante nisl ullamcorper lectus, elementum posuere ligula elit ornare mi. In ut magna tristique, pellentesque urna ornare, pretium leo. Maecenas porta consectetur lacus, ut interdum ligula blandit quis. Cras commodo elit a lorem tincidunt ornare. In at libero sagittis ante commodo placerat non sed tellus. Aliquam a lacus bibendum, commodo justo ac, luctus tellus.`;
}
