// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteDemo;

#nullable disable

namespace SQLiteDemo.Migrations
{
    [DbContext(typeof(SharingsContext))]
    [Migration("20231210120109_v1_2")]
    partial class v1_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("SQLiteDemo.PeopleRelation", b =>
                {
                    b.Property<Guid>("PersonAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonBId")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonAId");

                    b.HasIndex("PersonBId");

                    b.ToTable("PeopleRelations");
                });

            modelBuilder.Entity("SQLiteDemo.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SQLiteDemo.PeopleRelation", b =>
                {
                    b.HasOne("SQLiteDemo.Person", "PersonA")
                        .WithMany()
                        .HasForeignKey("PersonAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQLiteDemo.Person", "PersonB")
                        .WithMany()
                        .HasForeignKey("PersonBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonA");

                    b.Navigation("PersonB");
                });
#pragma warning restore 612, 618
        }
    }
}
